version: 2.1
orbs:
  node: circleci/node@5.1.0
jobs:
  build:
    docker:
      - image: node:14
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install Docker
          command: apt-get update && apt-get install -y docker.io
      - run:
          name: Build Docker Image
          command: |
            docker build -t fedor521/my-k8s-app:dev .
      - run:
          name: Push Docker Image
          command: |
            echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin
            docker push fedor521/my-k8s-app:dev