apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-k8s-app
  namespace: dev
  annotations:
      circleci.com/project-id: 25ab94b3-3bb2-4c5e-bc31-f3bf3be4a07a
  labels:
      circleci.com/component-name: my-k8s-app
      circleci.com/version: 1.0.0
      app: my-k8s-app
spec:
  selector:
    matchLabels:
      app: my-k8s-app
  template:
    metadata:
      labels:
        app: my-k8s-app
        circleci.com/component-name: my-k8s-app
        circleci.com/version: 1.0.0
    spec:
      containers:
      - name: my-k8s-app
        image: fedor521 my-k8s-app:dev
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
      restartPolicy: Always